name: recipe_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0
  pull_to_refresh: 2.0.0
  shimmer: ^2.0.0
  flutter_bloc: ^8.0.1
  json_annotation: ^4.1.0
  dio: ^4.0.6
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  effective_dart: ^1.3.2
  json_serializable: ^5.0.2

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
